### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by mfreeman451** [GetStream/stream-chat-go#194]
The github README for this project refers to methods that are not showing up such as CreateChannelWithMembers, i'm guessing these were removed but the docs havent been updated?

**Comment by peterdeme** [comment]
It's actually present: https://github.com/GetStream/stream-chat-go/blob/bb2463ad9479dbe077c17c8ef17183491ae0cad9/channel.go#L681

**Comment by sw360cab** [comment]
I think there is a bad sync with official [doc](https://getstream.io/chat/docs/go-golang/creating_channels/?language=go) either, since both (README too) are referring to method declarations without any `context.Context` param.

Check this line in README

https://github.com/GetStream/stream-chat-go/blob/86a4834eacdf23682b12fd59609658fbe020545f/README.md?plain=1#L57

**Comment by peterdeme** [comment]
https://github.com/GetStream/stream-chat-go/pull/224
